// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snvdhdwoxvyfjzeqyhoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudmRoZHdveHZ5Zmp6ZXF5aG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTM2NDksImV4cCI6MjA2Njk4OTY0OX0.8t2TSS0xcD1tYyE5_E7cZEhlIgCSBkER2K7mbhRNCDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});